name: build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run lint
      - run: npm run pdf
      - uses: actions/upload-artifact@v4
        with:
          name: resume
          path: resume.pdf
