name: release built pdf

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - run: npm ci
      - run: npm run pdf
      - uses: softprops/action-gh-release@v2
        with:
          files: resume.pdf
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
